name: napari_2pm_disp
channels:
  - conda-forge
dependencies:
  - python=3.8
  - scikit-image
  - jupyterlab
  - tifffile
  - imagecodecs
  - wxpython
  - pip
  - magicgui 
  - pyqt
  - pip:
    - aicsimageio
    - napari[all]
